CREATE TYPE "Ruolo" AS ENUM (
  'CLIENTE',
  'STAFF',
  'AMMINISTRATORE'
);

CREATE TYPE "StatoCamera" AS ENUM (
  'LIBERA',
  'OCCUPATA',
  'DA_PULIRE'
);

CREATE TYPE "StatoPrenotazione" AS ENUM (
  'CONFERMATA',
  'CHECKED_IN',
  'CHECKED_OUT',
  'CANCELLATA'
);

CREATE TABLE "utente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "nome" varchar NOT NULL,
  "cognome" varchar NOT NULL
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cittadinanza" varchar,
  "luogo" varchar,
  "dataNascita" varchar,
  "tipoDocumento" varchar,
  "numDocumento" varchar,
  "ref_utente" integer UNIQUE NOT NULL
);

CREATE TABLE "dipendente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruolo" "Ruolo" NOT NULL,
  "ref_sede" integer,
  "ref_utente" integer UNIQUE NOT NULL
);

CREATE TABLE "sede" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "location" varchar NOT NULL,
  "tassaSoggiorno" varchar NOT NULL
);

CREATE TABLE "camera" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ref_sede" integer NOT NULL,
  "numero" varchar NOT NULL,
  "postiLetto" integer NOT NULL,
  "prezzoBase" float NOT NULL,
  "tipologia" varchar NOT NULL DEFAULT 'Standard',
  "status" "StatoCamera" NOT NULL,
  "luce" boolean NOT NULL DEFAULT 0,
  "tapparelle" boolean NOT NULL DEFAULT 0,
  "temperatura" float NOT NULL DEFAULT 18
);

CREATE TABLE "service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar UNIQUE NOT NULL,
  "costo" float NOT NULL
);

CREATE TABLE "sede_service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ref_sede" integer,
  "ref_service" integer
);

CREATE TABLE "multimedia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "costo" float NOT NULL,
  "immagine" varchar,
  "descrizione" varchar,
  "voto" double NOT NULL
);

CREATE TABLE "prenotazione" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ref_cliente" integer NOT NULL,
  "ref_camera" integer NOT NULL,
  "dataInizio" date NOT NULL,
  "dataFine" date NOT NULL,
  "costo" float NOT NULL,
  "numeroOspiti" integer NOT NULL DEFAULT 1,
  "stato" "StatoPrenotazione" NOT NULL
);

CREATE TABLE "prenotazione_service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ref_prenotazione" integer,
  "ref_service" integer
);

CREATE TABLE "prenotazione_multimedia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ref_prenotazione" integer,
  "ref_multimedia" integer
);

CREATE TABLE "ospite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "cognome" varchar NOT NULL,
  "cittadinanza" varchar NOT NULL,
  "luogo" varchar NOT NULL,
  "dataNascita" date NOT NULL,
  "ref_prenotazione" integer NOT NULL
);

CREATE TABLE "nota" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "testo" varchar NOT NULL,
  "dataCreazione" timestamp NOT NULL,
  "ref_prenotazione" integer NOT NULL
);

COMMENT ON COLUMN "multimedia"."descrizione" IS 'length=1000';

COMMENT ON COLUMN "nota"."testo" IS 'length=1000';

ALTER TABLE "cliente" ADD FOREIGN KEY ("ref_utente") REFERENCES "utente" ("id");

ALTER TABLE "dipendente" ADD FOREIGN KEY ("ref_sede") REFERENCES "sede" ("id");

ALTER TABLE "dipendente" ADD FOREIGN KEY ("ref_utente") REFERENCES "utente" ("id");

ALTER TABLE "camera" ADD FOREIGN KEY ("ref_sede") REFERENCES "sede" ("id");

ALTER TABLE "sede_service" ADD FOREIGN KEY ("ref_sede") REFERENCES "sede" ("id");

ALTER TABLE "sede_service" ADD FOREIGN KEY ("ref_service") REFERENCES "service" ("id");

ALTER TABLE "prenotazione" ADD FOREIGN KEY ("ref_cliente") REFERENCES "cliente" ("id");

ALTER TABLE "prenotazione" ADD FOREIGN KEY ("ref_camera") REFERENCES "camera" ("id");

ALTER TABLE "prenotazione_service" ADD FOREIGN KEY ("ref_prenotazione") REFERENCES "prenotazione" ("id");

ALTER TABLE "prenotazione_service" ADD FOREIGN KEY ("ref_service") REFERENCES "service" ("id");

ALTER TABLE "prenotazione_multimedia" ADD FOREIGN KEY ("ref_prenotazione") REFERENCES "prenotazione" ("id");

ALTER TABLE "prenotazione_multimedia" ADD FOREIGN KEY ("ref_multimedia") REFERENCES "multimedia" ("id");

ALTER TABLE "ospite" ADD FOREIGN KEY ("ref_prenotazione") REFERENCES "prenotazione" ("id");

ALTER TABLE "nota" ADD FOREIGN KEY ("ref_prenotazione") REFERENCES "prenotazione" ("id");
